# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb7a55e24ae56f2c241eb65ecd283cda11909b196462e428a5b43da709624434e6f0ee9a12f81c9329fa9a5bfe26a4a3236a88ea3621a7446e22e24dec8eeddf

test:
  secret_key_base: cdba8ef8a04bda9ae2f84c31697bfbb475cb4f47157fb6d180db2b7b4fe6142b92ebaa76da8868ad6080dda85cc76803dee892fbb90e5c346f93f43aea5f22b7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
